apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spring-boot-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
